#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate the Drona Enterprises Profitability Suite — Technical Architecture
& Implementation Report as a multi-page PDF (ReportLab).

Pipeline:
  1. Build body PDF with TocDocTemplate + multiBuild(story).
  2. Cover (HTML/Playwright) is rendered separately and merged via pypdf.
"""
import os
import sys
import hashlib
import platform
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch, mm
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT, TA_JUSTIFY
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak, KeepTogether,
    Table, TableStyle, Image, HRFlowable, CondPageBreak,
)
from reportlab.platypus.tableofcontents import TableOfContents

# ─────────────────────────────────────────────────────────────────────
# Paths
# ─────────────────────────────────────────────────────────────────────
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
PDF_SKILL_DIR = "/home/z/my-project/skills/pdf"

# Inject skill scripts dir so install_font_fallback() is importable
_scripts = os.path.join(PDF_SKILL_DIR, "scripts")
if _scripts not in sys.path:
    sys.path.insert(0, _scripts)

# ─────────────────────────────────────────────────────────────────────
# Cascade Palette (auto-generated by design_engine.py palette-cascade)
# ─────────────────────────────────────────────────────────────────────
PAGE_BG       = colors.HexColor('#f0f0ee')
SECTION_BG    = colors.HexColor('#f1f1ef')
CARD_BG       = colors.HexColor('#f1f0ed')
TABLE_STRIPE  = colors.HexColor('#f3f2f0')
HEADER_FILL   = colors.HexColor('#7a6d47')
COVER_BLOCK   = colors.HexColor('#5c5746')
BORDER        = colors.HexColor('#c8c0a6')
ICON          = colors.HexColor('#99854a')
ACCENT        = colors.HexColor('#9f8434')
ACCENT_2      = colors.HexColor('#5c42aa')
TEXT_PRIMARY  = colors.HexColor('#171715')
TEXT_MUTED    = colors.HexColor('#85827b')
SEM_SUCCESS   = colors.HexColor('#3b7a50')
SEM_WARNING   = colors.HexColor('#937841')
SEM_ERROR     = colors.HexColor('#9c554f')
SEM_INFO      = colors.HexColor('#4d6b89')

TABLE_HEADER_COLOR = HEADER_FILL
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = TABLE_STRIPE

# ─────────────────────────────────────────────────────────────────────
# Font registration
# ─────────────────────────────────────────────────────────────────────
_IS_MAC = platform.system() == 'Darwin'
if _IS_MAC:
    FONT_DIR = os.path.expanduser('~/.openclaw/workspace/fonts')
else:
    FONT_DIR = '/usr/share/fonts'

pdfmetrics.registerFont(TTFont('NotoSerifSC', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif', f'{FONT_DIR}/truetype/freefont/FreeSerif.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Bold', f'{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Italic', f'{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-BoldItalic', f'{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', f'{FONT_DIR}/truetype/dejavu/DejaVuSansMono.ttf'))

registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')
registerFontFamily('FreeSerif',
                   normal='FreeSerif',
                   bold='FreeSerif-Bold',
                   italic='FreeSerif-Italic',
                   boldItalic='FreeSerif-BoldItalic')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans')

from pdf import install_font_fallback  # noqa: E402
install_font_fallback()

# ─────────────────────────────────────────────────────────────────────
# Geometry
# ─────────────────────────────────────────────────────────────────────
PAGE_W, PAGE_H = A4
LEFT_M  = 0.85 * inch
RIGHT_M = 0.85 * inch
TOP_M   = 0.85 * inch
BOT_M   = 0.85 * inch
AVAIL_W = PAGE_W - LEFT_M - RIGHT_M
AVAIL_H = PAGE_H - TOP_M - BOT_M

H1_ORPHAN = AVAIL_H * 0.15
MAX_KEEP_H = AVAIL_H * 0.40

# ─────────────────────────────────────────────────────────────────────
# Paragraph styles
# ─────────────────────────────────────────────────────────────────────
styles = getSampleStyleSheet()

H1 = ParagraphStyle('H1', fontName='FreeSerif-Bold', fontSize=20, leading=26,
                    textColor=TEXT_PRIMARY, spaceBefore=18, spaceAfter=10,
                    alignment=TA_LEFT)
H2 = ParagraphStyle('H2', fontName='FreeSerif-Bold', fontSize=14.5, leading=20,
                    textColor=HEADER_FILL, spaceBefore=14, spaceAfter=6,
                    alignment=TA_LEFT)
H3 = ParagraphStyle('H3', fontName='FreeSerif-Bold', fontSize=12, leading=16,
                    textColor=TEXT_PRIMARY, spaceBefore=10, spaceAfter=4,
                    alignment=TA_LEFT)
BODY = ParagraphStyle('Body', fontName='FreeSerif', fontSize=10.5, leading=16,
                      textColor=TEXT_PRIMARY, spaceBefore=0, spaceAfter=8,
                      alignment=TA_JUSTIFY)
BODY_LEFT = ParagraphStyle('BodyLeft', parent=BODY, alignment=TA_LEFT)
BULLET = ParagraphStyle('Bullet', parent=BODY, leftIndent=18, bulletIndent=4,
                        spaceAfter=4)
CAPTION = ParagraphStyle('Caption', fontName='FreeSerif-Italic', fontSize=9,
                          leading=12, textColor=TEXT_MUTED, alignment=TA_CENTER,
                          spaceBefore=4, spaceAfter=10)
TOC_TITLE = ParagraphStyle('TOCTitle', fontName='FreeSerif-Bold', fontSize=22,
                           leading=28, textColor=TEXT_PRIMARY, alignment=TA_LEFT,
                           spaceAfter=18)

# Table styles
TBL_HEADER = ParagraphStyle('TblHeader', fontName='FreeSerif-Bold', fontSize=9.5,
                            leading=13, textColor=colors.white, alignment=TA_LEFT)
TBL_HEADER_C = ParagraphStyle('TblHeaderC', parent=TBL_HEADER, alignment=TA_CENTER)
TBL_CELL = ParagraphStyle('TblCell', fontName='FreeSerif', fontSize=9, leading=12.5,
                          textColor=TEXT_PRIMARY, alignment=TA_LEFT)
TBL_CELL_C = ParagraphStyle('TblCellC', parent=TBL_CELL, alignment=TA_CENTER)
TBL_CELL_R = ParagraphStyle('TblCellR', parent=TBL_CELL, alignment=TA_RIGHT)
TBL_CELL_MONO = ParagraphStyle('TblCellMono', fontName='DejaVuSans', fontSize=8.5,
                                leading=12, textColor=TEXT_PRIMARY, alignment=TA_LEFT)

# Callout style
CALLOUT_VAL = ParagraphStyle('CalloutVal', fontName='FreeSerif-Bold', fontSize=22,
                              leading=26, textColor=ACCENT, alignment=TA_CENTER)
CALLOUT_LBL = ParagraphStyle('CalloutLbl', fontName='FreeSerif', fontSize=9,
                              leading=12, textColor=TEXT_MUTED, alignment=TA_CENTER)

# TOC level styles
TOC_L0 = ParagraphStyle('TOCL0', fontName='FreeSerif-Bold', fontSize=11.5, leading=18,
                        leftIndent=0, textColor=TEXT_PRIMARY)
TOC_L1 = ParagraphStyle('TOCL1', fontName='FreeSerif', fontSize=10, leading=15,
                        leftIndent=20, textColor=TEXT_MUTED)

# ─────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────
def add_heading(text, style, level=0):
    key = 'h_' + hashlib.md5(text.encode()).hexdigest()[:10]
    p = Paragraph(f'<a name="{key}"/>{text}', style)
    p.bookmark_name = key
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p


def safe_keep(elements):
    """Wrap elements in KeepTogether only if they fit; otherwise split."""
    total_h = 0
    for el in elements:
        try:
            _, h = el.wrap(AVAIL_W, AVAIL_H)
            total_h += h
        except Exception:
            total_h += 30
    if total_h <= MAX_KEEP_H:
        return [KeepTogether(elements)]
    elif len(elements) >= 2:
        return [KeepTogether(elements[:2])] + list(elements[2:])
    return list(elements)


def h1(text):
    return [CondPageBreak(H1_ORPHAN), add_heading(text, H1, level=0),
            HRFlowable(width="100%", thickness=1.4, color=ACCENT,
                       spaceBefore=2, spaceAfter=12)]


def h2(text):
    return [CondPageBreak(60), add_heading(text, H2, level=1)]


def h3(text):
    return [add_heading(text, H3, level=1)]


def p(text):
    # Use a non-breaking space before em-dashes so they never start a wrapped
    # line (pdf_qa.py flags em-dash line-start as a punctuation warning).
    text = text.replace(' — ', '\u00A0— ')
    return Paragraph(text, BODY)


def pl(text):
    text = text.replace(' — ', '\u00A0— ')
    return Paragraph(text, BODY_LEFT)


def bullet(text):
    text = text.replace(' — ', '\u00A0— ')
    return Paragraph(text, BULLET, bulletText=u'\u2022')


def caption(text):
    return Paragraph(text, CAPTION)


def fit_image(path, max_w=None, max_h=None):
    from PIL import Image as PILImage
    if max_w is None:
        max_w = AVAIL_W
    if max_h is None:
        max_h = AVAIL_H * 0.45
    pil = PILImage.open(path)
    ow, oh = pil.size
    rw = max_w / ow if ow > max_w else 1.0
    rh = max_h / oh if oh > max_h else 1.0
    r = min(rw, rh, 1.0)
    return Image(path, width=ow * r, height=oh * r)


def make_table(data_rows, col_ratios, header=True, h_align='CENTER'):
    """data_rows: list of lists of Paragraph or Image. col_ratios sum to 1.0."""
    col_widths = [r * AVAIL_W for r in col_ratios]
    t = Table(data_rows, colWidths=col_widths, hAlign=h_align, repeatRows=1 if header else 0)
    sty = [
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('GRID', (0, 0), (-1, -1), 0.35, BORDER),
    ]
    if header:
        sty += [
            ('BACKGROUND', (0, 0), (-1, 0), HEADER_FILL),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('TOPPADDING', (0, 0), (-1, 0), 7),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 7),
        ]
        for i in range(1, len(data_rows)):
            if i % 2 == 1:
                sty.append(('BACKGROUND', (0, i), (-1, i), TABLE_ROW_ODD))
            else:
                sty.append(('BACKGROUND', (0, i), (-1, i), TABLE_ROW_EVEN))
    t.setStyle(TableStyle(sty))
    return t


def callout(value, label, color=ACCENT, width=130):
    val_style = ParagraphStyle('cv', parent=CALLOUT_VAL, textColor=color)
    cell = Table(
        [[Paragraph(value, val_style)],
         [Paragraph(label, CALLOUT_LBL)]],
        colWidths=[width],
    )
    cell.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
        ('BOX', (0, 0), (-1, -1), 0.6, BORDER),
        ('LINEBEFORE', (0, 0), (0, -1), 3, color),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    return cell


def callout_row(items, total_width=None):
    """items = list of (value, label, color) tuples. Render side by side."""
    if total_width is None:
        total_width = AVAIL_W
    n = len(items)
    col_w = total_width / n
    cells = [callout(v, l, c, width=col_w - 8) for v, l, c in items]
    t = Table([cells], colWidths=[col_w] * n, hAlign='CENTER')
    t.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 3),
        ('RIGHTPADDING', (0, 0), (-1, -1), 3),
        ('TOPPADDING', (0, 0), (-1, -1), 0),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
    ]))
    return t


# ─────────────────────────────────────────────────────────────────────
# TocDocTemplate + Header/Footer
# ─────────────────────────────────────────────────────────────────────
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))


def header_footer(canvas, doc):
    canvas.saveState()
    # Header: title (left) + accent rule
    canvas.setFont('FreeSerif', 8)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(LEFT_M, PAGE_H - TOP_M + 22,
                      'Drona Profitability Suite  -  Technical Architecture & Implementation Report')
    canvas.setFont('FreeSerif-Italic', 8)
    # Avoid ending the header line with a number (toc_validate.py would parse
    # the trailing digits as a page-number reference and fail the TOC check).
    canvas.drawRightString(PAGE_W - RIGHT_M, PAGE_H - TOP_M + 22, 'Z.ai Engineering  -  v1.0')
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.6)
    canvas.line(LEFT_M, PAGE_H - TOP_M + 16, PAGE_W - RIGHT_M, PAGE_H - TOP_M + 16)

    # Footer: rule + page number
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.4)
    canvas.line(LEFT_M, BOT_M - 18, PAGE_W - RIGHT_M, BOT_M - 18)
    canvas.setFont('FreeSerif', 8)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(LEFT_M, BOT_M - 30, '© 2025 Drona Enterprises · Multi-tenant Profitability Suite')
    canvas.setFont('FreeSerif-Bold', 8)
    canvas.setFillColor(TEXT_PRIMARY)
    # Page numbers offset by +1 because cover will be inserted as page 1
    page_num = doc.page + 1
    canvas.drawRightString(PAGE_W - RIGHT_M, BOT_M - 30, f'Page {page_num}')
    canvas.restoreState()


# ─────────────────────────────────────────────────────────────────────
# Content sections
# ─────────────────────────────────────────────────────────────────────
def build_story():
    story = []

    # ---- TOC page ----
    story.append(Paragraph('Table of Contents', TOC_TITLE))
    story.append(HRFlowable(width="100%", thickness=1.2, color=ACCENT, spaceAfter=14))
    toc = TableOfContents()
    toc.levelStyles = [TOC_L0, TOC_L1]
    story.append(toc)
    story.append(PageBreak())

    # ============================================================
    # CHAPTER 1 — Executive Summary
    # ============================================================
    story.extend(h1('Chapter 1 — Executive Summary'))

    story.append(p(
        'The <b>Drona Enterprises Profitability Suite</b> is a multi-tenant Software-as-a-Service '
        'application purpose-built for staffing and consulting-style organisations that bill clients '
        'and need to track per-client profitability. The suite lets a parent company (Drona Enterprises) '
        'operate a consolidated group view while simultaneously giving each tenant subsidiary '
        '(Drona Logitech, Drona Valuechain) its own isolated financial workspace. Every revenue '
        'invoice, every employee cost entry, every expense and every allocation is owned by exactly '
        'one tenant, and backend query-level filtering guarantees that no tenant can ever read or '
        'mutate another tenant\'s data — even by direct API call.'
    ))

    story.append(p(
        'The platform delivers three concrete value propositions. <b>First</b>, it consolidates '
        'revenue, employee cost, expense, and allocation data into a single dashboard with four '
        'KPI cards and four charts that update in real time as new transactions are added. '
        '<b>Second</b>, it allocates employee cost to clients proportionally based on '
        'Employee-Client Allocation percentages, producing a per-client profitability breakdown '
        'that is otherwise tedious to compute by hand. <b>Third</b>, it enforces role-based '
        'access control with three roles (Group Admin, Company Admin, Standard User) so that '
        'sensitive management views (Companies module, Reports) are restricted to admins while '
        'operational views (Clients, Revenue, Employees, Allocations, Expenses) remain accessible '
        'to all authenticated users.'
    ))

    story.append(p(
        'The application is built on <b>Next.js 16.1.3</b> with the App Router, TypeScript 5, '
        'Prisma 6.19.2 with a SQLite database, Tailwind CSS 4, and the shadcn/ui component '
        'library. Eight user-facing modules are wired into a single-page AppShell with a '
        'responsive sidebar that collapses to a horizontal scroller on mobile. The schema '
        'comprises <b>13 Prisma models</b>, including a self-referencing Company hierarchy '
        'and an EmployeeClientAllocation junction table that powers the cost-allocation engine.'
    ))

    story.append(Spacer(1, 6))
    story.append(p('<b>Snapshot of seeded live data (April – September 2024, group consolidated):</b>'))
    story.append(Spacer(1, 6))
    story.append(callout_row([
        ('₹ 21.12 Cr', 'Total Revenue', SEM_SUCCESS),
        ('₹ 5.53 Cr', 'Total Cost', SEM_ERROR),
        ('₹ 15.59 Cr', 'Total Profit', ACCENT),
        ('73.8%', 'Profit Margin', SEM_WARNING),
    ]))
    story.append(Spacer(1, 12))

    story.append(p(
        'These numbers are produced directly by the <font name="DejaVuSans">GET /api/dashboard</font> '
        'endpoint when logged in as the Group Admin (group.admin@drona.com), which aggregates '
        'revenue rows, employee cost rows, allocations, and expenses across both tenants. The '
        'application ships with five demo user accounts spanning all three roles and both tenants, '
        'so reviewers can verify role gating and tenant isolation immediately after running '
        '<font name="DejaVuSans">bun run db:seed</font>. The codebase passes <font name="DejaVuSans">bun run lint</font> '
        'with zero errors, and every API route returns HTTP 200 in the browser-verified smoke test.'
    ))

    story.append(PageBreak())

    # ============================================================
    # CHAPTER 2 — System Overview
    # ============================================================
    story.extend(h1('Chapter 2 — System Overview'))

    story.append(p(
        'The Drona Profitability Suite is an internal ERP for a class of business that is '
        'common across India\'s mid-market IT services sector: a parent group runs several '
        'operating subsidiaries, each subsidiary bills a handful of clients on a monthly basis, '
        'and each subsidiary employs engineers who split their time across multiple clients. '
        'Tracking per-client profitability in this model is non-trivial — revenue is straightforward '
        '(it is billed per client per invoice), but cost is a function of which employees are '
        'allocated to which client and at what percentage. The suite exists to make this calculation '
        'transparent, repeatable, and auditable.'
    ))

    story.extend(h2('2.1 What the System Does'))
    story.append(p(
        'The platform captures five core business entities: <b>Revenue</b> (invoice entries billed to '
        'a client), <b>Employees</b> (workforce master data), <b>Employee Cost</b> (salary, allowance, '
        'overtime, benefit and other cost rows tagged to an employee and date), <b>Allocations</b> '
        '(employee-to-client percentage allocations over a time window), and <b>Expenses</b> (categorised '
        'operational, administrative or capital expenses booked against a tenant). On top of these '
        'entities, the dashboard and reports modules derive four headline KPIs and a set of charts '
        'and per-client profitability breakdowns.'
    ))

    story.extend(h2('2.2 Multi-Tenant Model'))
    story.append(p(
        'The system follows a <b>shared application + isolated data</b> multi-tenant pattern. A '
        'single Next.js codebase serves every tenant; a single SQLite database file holds every '
        'tenant\'s rows; and isolation is enforced logically by filtering every Prisma query on '
        '<font name="DejaVuSans">companyId IN (accessibleIds)</font>. The Parent company '
        '(Drona Enterprises, code <font name="DejaVuSans">DRONA-ENT</font>) controls two Tenant '
        'companies: Drona Logitech (<font name="DejaVuSans">DRONA-LOG</font>) and Drona Valuechain '
        '(<font name="DejaVuSans">DRONA-VAL</font>). A Group Admin user attached to the parent '
        'company can see a consolidated view across all tenants; tenant-attached users see only '
        'their own tenant\'s rows.'
    ))

    story.extend(h2('2.3 Tenant Isolation Is Backend-Enforced'))
    story.append(p(
        'Critically, tenant isolation is <b>not</b> a UI-level hide. The function '
        '<font name="DejaVuSans">getAccessibleCompanyIds(user)</font> in '
        '<font name="DejaVuSans">src/lib/auth.ts</font> returns either all company IDs (for a '
        'Group Admin) or the user\'s own <font name="DejaVuSans">companyId</font> wrapped in '
        'a single-element array. Every API route — without exception — calls this function and '
        'filters its Prisma <font name="DejaVuSans">findMany</font> / <font name="DejaVuSans">create</font> '
        'queries against the returned set. Write operations additionally verify that the target '
        '<font name="DejaVuSans">companyId</font> is in the accessible set before persisting. '
        'A tenant user attempting <font name="DejaVuSans">GET /api/clients?companyId=otherTenantId</font> '
        'will receive an empty result set, not the other tenant\'s clients.'
    ))

    story.extend(h2('2.4 Three Roles'))
    story.append(p(
        'Authentication produces a session user with one of three roles: '
        '<b>GROUP_ADMIN</b> (sees Companies module + Reports, can pick any tenant in the filter, '
        'can create new tenants under the parent), <b>COMPANY_ADMIN</b> (full access to their '
        'own tenant\'s operational modules — Clients, Revenue, Employees, Allocations, Expenses — '
        'plus the Reports module), and <b>STANDARD_USER</b> (view-only access to operational '
        'modules; Add buttons are disabled and the Reports and Companies modules are hidden from '
        'the sidebar). The role is stored on the User row and surfaced to the frontend via '
        '<font name="DejaVuSans">GET /api/auth/me</font>; the AppShell filters the navigation '
        'array by role on the client side, and the API routes re-check authorisation on every request.'
    ))

    story.extend(h2('2.5 Business Domain'))
    story.append(p(
        'The suite targets the staffing / consulting / professional-services domain. The minimum '
        'viable data model assumes that revenue is billed per client per month (the Revenue entity '
        'has a date, an invoice number, a quantity and a rate, with amount auto-computed when not '
        'overridden); that employees carry a monthly cost (the EmployeeCost entity records SALARY, '
        'ALLOWANCE, OVERTIME, BENEFIT and OTHER cost types); that employees are allocated to clients '
        'with a percentage split (an EmployeeClientAllocation junction table); and that other operating '
        'expenses are categorised (the ExpenseCategory entity is tenant-owned with a type tag of '
        'OPERATIONAL, ADMINISTRATIVE or CAPITAL). The dashboard\'s cost allocation engine is what '
        'turns these raw inputs into a meaningful profit-per-client view.'
    ))

    story.append(PageBreak())

    # ============================================================
    # CHAPTER 3 — System Architecture
    # ============================================================
    story.extend(h1('Chapter 3 — System Architecture'))

    story.extend(h2('3.1 Overall Architecture'))
    story.append(p(
        'The architecture follows a three-tier hierarchy: one Parent company (Drona Enterprises) '
        'controls N Tenant companies (currently two: Drona Logitech and Drona Valuechain). Each '
        'tenant owns its own Clients, Employees, Revenue entries, Employee Cost entries, Allocations, '
        'Expenses, and Expense Categories. The application shares a single codebase and a single '
        'SQLite database file; tenant isolation is enforced logically by filtering every Prisma '
        'query on <font name="DejaVuSans">companyId</font>. The figure below visualises the '
        'hierarchy and the resource ownership model.'
    ))

    story.append(Spacer(1, 6))
    story.append(fit_image(os.path.join(BASE_DIR, 'diagram_hierarchy.png'),
                            max_w=AVAIL_W, max_h=AVAIL_H * 0.45))
    story.append(caption(
        'Figure 1. Multi-tenant hierarchy. Drona Enterprises (PARENT) controls Drona Logitech and '
        'Drona Valuechain (TENANT). Each tenant owns its Clients, Employees, Revenue, EmployeeCost, '
        'Allocations, Expenses and Users. Isolation is enforced at the API layer.'
    ))

    story.extend(h2('3.2 Login & Access Flow'))
    story.append(p(
        'Authentication uses a classic cookie-session pattern, not JWT. The user enters an email '
        'and password on the login screen; <font name="DejaVuSans">POST /api/auth/login</font> '
        'verifies the credentials against the User table (the demo password hash is the literal '
        'reverse of the password prefixed with <font name="DejaVuSans">demo$</font> — explicitly '
        'insecure, suitable only for demo), and on success creates a Session row with a random '
        'UUID token plus a 12-hour expiry. The token is set as an httpOnly cookie named '
        '<font name="DejaVuSans">drona_session</font> with <font name="DejaVuSans">sameSite=lax</font> '
        'and <font name="DejaVuSans">path=/</font>. Subsequent requests carry the cookie; '
        '<font name="DejaVuSans">getCurrentUser()</font> reads it, looks up the Session row, '
        'checks the expiry, and returns the session user with their company attached. The frontend '
        'stores the user object in a Zustand store and renders the AppShell with role-gated '
        'navigation.'
    ))

    story.extend(h2('3.3 User Roles & Permissions (RBAC)'))
    story.append(p(
        'Three roles are defined. The table below shows what each role can see and do.'
    ))
    role_data = [
        [Paragraph('<b>Role</b>', TBL_HEADER),
         Paragraph('<b>Modules Visible</b>', TBL_HEADER),
         Paragraph('<b>Key Capabilities</b>', TBL_HEADER)],
        [Paragraph('<b>GROUP_ADMIN</b>', TBL_CELL),
         Paragraph('Dashboard, Companies, Clients, Revenue, Employees, Allocations, Expenses, Reports', TBL_CELL),
         Paragraph('Consolidated view across all tenants. Picks any tenant in the filter dropdown. '
                   'Creates new tenants (POST /api/companies with type=TENANT). Sees Companies module '
                   'and Reports module.', TBL_CELL)],
        [Paragraph('<b>COMPANY_ADMIN</b>', TBL_CELL),
         Paragraph('Dashboard, Clients, Revenue, Employees, Allocations, Expenses, Reports', TBL_CELL),
         Paragraph('Full read-write access to their own tenant\'s operational modules. Cannot manage '
                   'other tenants. Sees Reports module scoped to their own tenant.', TBL_CELL)],
        [Paragraph('<b>STANDARD_USER</b>', TBL_CELL),
         Paragraph('Dashboard, Clients, Revenue, Employees, Allocations, Expenses', TBL_CELL),
         Paragraph('View-only access. Add buttons are disabled across all modules ("View-only access" '
                   'badge shown). Cannot see Companies or Reports modules.', TBL_CELL)],
    ]
    story.append(Spacer(1, 6))
    story.append(make_table(role_data, [0.20, 0.32, 0.48]))
    story.append(caption('Table 1. Role-based access control matrix. Role is stored on the User row and enforced both in the AppShell sidebar and on the backend API routes.'))

    story.extend(h2('3.4 Business Modules'))
    story.append(p(
        'The AppShell renders eight user-facing modules. Each module is a dedicated React '
        'component mounted via a switch statement on the active module key. The table below '
        'lists each module, its purpose, and its role visibility.'
    ))
    modules_data = [
        [Paragraph('<b>Module</b>', TBL_HEADER),
         Paragraph('<b>Purpose</b>', TBL_HEADER),
         Paragraph('<b>Key Fields / Actions</b>', TBL_HEADER),
         Paragraph('<b>Roles</b>', TBL_HEADER_C)],
        [Paragraph('Dashboard', TBL_CELL),
         Paragraph('KPI cards + 4 charts + per-client profitability table', TBL_CELL),
         Paragraph('Total Revenue, Total Cost, Total Profit, Margin; revenue-by-client donut; '
                   'cost-by-category donut; profit-by-client bar; profit-trend composed line', TBL_CELL),
         Paragraph('All', TBL_CELL_C)],
        [Paragraph('Companies', TBL_CELL),
         Paragraph('Parent + tenant hierarchy viewer; create tenant; custom columns table', TBL_CELL),
         Paragraph('Parent card with aggregate KPIs, tenant cards with per-tenant stats, '
                   'Add Tenant dialog, Custom Columns popover (8 toggleable columns)', TBL_CELL),
         Paragraph('GROUP_ADMIN', TBL_CELL_C)],
        [Paragraph('Clients', TBL_CELL),
         Paragraph('Client master data with status filter and Add dialog', TBL_CELL),
         Paragraph('Name, Code, Type, Location, Contract Value, Contact; status pills; Add '
                   'dialog with company picker for Group Admin', TBL_CELL),
         Paragraph('All', TBL_CELL_C)],
        [Paragraph('Revenue', TBL_CELL),
         Paragraph('Invoice entries billed per client', TBL_CELL),
         Paragraph('Date, Invoice #, Description, Qty, Rate, Amount (auto-computed). KPI cards '
                   'show entries count, total amount, period.', TBL_CELL),
         Paragraph('All', TBL_CELL_C)],
        [Paragraph('Employees', TBL_CELL),
         Paragraph('Workforce master data with department/type/status filters', TBL_CELL),
         Paragraph('Name, Code, Type, Department, Location, Designation, Salary, Joining Date, '
                   'Allocation count, Cost count, Status', TBL_CELL),
         Paragraph('All', TBL_CELL_C)],
        [Paragraph('Allocations', TBL_CELL),
         Paragraph('Employee-to-client percentage allocations, grouped by employee', TBL_CELL),
         Paragraph('Employee card with stacked-bar visualisation, Total Allocation % badge '
                   '(green=100%, amber=incomplete, rose=over 100%), Add / Remove actions', TBL_CELL),
         Paragraph('All', TBL_CELL_C)],
        [Paragraph('Expenses', TBL_CELL),
         Paragraph('Categorised operational / administrative / capital expenses', TBL_CELL),
         Paragraph('Date, Category (with type-coloured badge), Description, Amount. Summary '
                   'cards: total, by-type breakdown, entry count.', TBL_CELL),
         Paragraph('All', TBL_CELL_C)],
        [Paragraph('Reports', TBL_CELL),
         Paragraph('Per-company profitability report with cost-breakdown explanation', TBL_CELL),
         Paragraph('Calculation flow banner (Revenue - Cost = Profit -> Margin), per-company '
                   'table with margin badges, cost-breakdown card explaining allocation logic', TBL_CELL),
         Paragraph('GROUP_ADMIN, COMPANY_ADMIN', TBL_CELL_C)],
    ]
    story.append(Spacer(1, 6))
    story.append(make_table(modules_data, [0.13, 0.21, 0.50, 0.16]))
    story.append(caption('Table 2. The eight user-facing business modules. Module "Employee Cost" was removed in iteration 2 but the underlying Prisma model and API route are retained because the Dashboard aggregates employee costs into Total Cost.'))

    story.extend(h2('3.5 Dashboard & Analytics'))
    story.append(p(
        'The Dashboard module is the landing page after login. It is composed of four bands. '
        'At the top are <b>four KPI cards</b>: Total Revenue, Total Cost, Total Profit and '
        'Profit Margin. Beneath them is a <b>profitability flow banner</b> rendering the '
        'formula as four boxes — Revenue (emerald) − Cost (rose) = Profit (primary navy) → '
        'Margin (amber). Below the banner are <b>four charts</b>: a Revenue-by-Client donut '
        '(top 6 + Others bucket), a Cost-by-Category donut (employee cost types plus other '
        'expense categories), a Profit-by-Client bar chart, and a Profit Trend composed chart '
        'showing monthly revenue, cost and profit lines. At the bottom is a '
        '<b>per-client profitability breakdown table</b> sorted by profit descending.'
    ))

    story.extend(h2('3.6 Database Schema'))
    story.append(p(
        'The Prisma schema defines 13 models covering auth, tenancy, reference data and the '
        'business entities. Key relationships are: one Company has many Clients; one Client '
        'has many Revenue entries; the Employee-ClientAllocation junction implements a many-to-many '
        'between Employee and Client with an allocation-percent attribute; one Employee has many '
        'EmployeeCost rows; one ExpenseCategory has many Expenses; the Company hierarchy is '
        'modelled by a self-referencing <font name="DejaVuSans">parentId</font> with the '
        '<font name="DejaVuSans">"CompanyHierarchy"</font> relation name. The full ER overview '
        'is presented in Chapter 7 (Data Model).'
    ))

    story.append(PageBreak())

    # ============================================================
    # CHAPTER 4 — How It Works
    # ============================================================
    story.extend(h1('Chapter 4 — How It Works'))

    story.extend(h2('4.1 Authentication & Session Management'))
    story.append(p(
        'The auth subsystem lives in <font name="DejaVuSans">src/lib/auth.ts</font> and exposes '
        'four functions: <font name="DejaVuSans">login(email, password)</font>, '
        '<font name="DejaVuSans">logout()</font>, <font name="DejaVuSans">getCurrentUser()</font>, '
        'and <font name="DejaVuSans">getAccessibleCompanyIds(user)</font>. The login flow is the '
        'most important: it looks up the user by email (case-insensitive, trimmed), verifies the '
        'password against the stored <font name="DejaVuSans">passwordHash</font>, creates a Session '
        'row with a random UUID token and a 12-hour expiry timestamp, and sets the '
        '<font name="DejaVuSans">drona_session</font> httpOnly cookie on the response. The session '
        'token is stored server-side in the Session table, so the application can revoke a session '
        'by deleting the row (which <font name="DejaVuSans">logout()</font> does).'
    ))

    story.append(p(
        'Password verification uses a deliberately demo-grade scheme: the stored hash is the literal '
        'byte-reversal of the password prefixed with the marker <font name="DejaVuSans">demo$</font>. '
        'This is documented as unsuitable for production; a real deployment would replace '
        '<font name="DejaVuSans">verifyPassword</font> with bcrypt or argon2 and migrate the '
        'existing hashes on next login. The session TTL is hard-coded at 12 hours '
        '(<font name="DejaVuSans">1000 * 60 * 60 * 12</font> ms). On every authenticated request, '
        '<font name="DejaVuSans">getCurrentUser()</font> checks that the session row exists, that '
        '<font name="DejaVuSans">expiresAt</font> has not passed, and that the user is still marked '
        '<font name="DejaVuSans">active</font>; any failure returns null and the API route replies '
        'with HTTP 401 Unauthorized.'
    ))

    story.extend(h2('4.2 Tenant Isolation Enforcement'))
    story.append(p(
        'The function <font name="DejaVuSans">getAccessibleCompanyIds(user)</font> is the '
        'cornerstone of multi-tenant isolation. Its implementation is 6 lines of code:'
    ))
    story.append(p(
        '<font name="DejaVuSans">if (user.role === "GROUP_ADMIN") { '
        'return (await db.company.findMany()).map(c => c.id); } '
        'return user.companyId ? [user.companyId] : [];</font>'
    ))
    story.append(p(
        'For a Group Admin, it returns every Company ID in the database (parent + all tenants). '
        'For any other role, it returns a single-element array containing the user\'s own '
        '<font name="DejaVuSans">companyId</font> (or an empty array if the user is parent-attached '
        'but is not a Group Admin — a degenerate case that should not occur in seeded data). '
        'Every API route in <font name="DejaVuSans">src/app/api/</font> calls this function once '
        'at the top of its handler and then filters every Prisma query with '
        '<font name="DejaVuSans">where: { companyId: { in: accessibleIds } }</font> (or the '
        'equivalent relation filter, e.g. '
        '<font name="DejaVuSans">{ client: { companyId: { in: accessibleIds } } }</font> for '
        'revenue). Write operations additionally check that the target company is in the accessible '
        'set before creating. This is the core tenant-isolation guarantee.'
    ))

    story.extend(h2('4.3 Data Flow: API Request → Filtered Data'))
    story.append(p(
        'Consider a typical request: <font name="DejaVuSans">GET /api/clients?status=ACTIVE</font>. '
        'The handler executes the following five-step pipeline:'
    ))
    story.append(p(
        '<b>(1) Cookie auth</b> — <font name="DejaVuSans">getCurrentUser()</font> reads the '
        '<font name="DejaVuSans">drona_session</font> cookie, looks up the Session row, validates '
        'expiry, returns the user. <b>(2) Tenant scoping</b> — '
        '<font name="DejaVuSans">getAccessibleCompanyIds(user)</font> returns either every '
        'company ID (Group Admin) or the user\'s single <font name="DejaVuSans">companyId</font>. '
        '<b>(3) Query parsing</b> — the handler reads <font name="DejaVuSans">companyId</font>, '
        '<font name="DejaVuSans">locationId</font>, <font name="DejaVuSans">clientTypeId</font>, '
        '<font name="DejaVuSans">status</font> from the URL search params (the '
        '<font name="DejaVuSans">companyId</font> param is honoured only if the user is a '
        'Group Admin and the picked ID is in the accessible set; otherwise it is silently '
        'ignored to preserve the user\'s scope). <b>(4) Prisma findMany</b> — the combined '
        'where clause is built by merging the tenant filter with the optional filters from '
        'step 3, then <font name="DejaVuSans">db.client.findMany({ where, include: { ... }, '
        'orderBy: { name: "asc" } })</font> is executed. <b>(5) Response</b> — the rows are '
        'returned as JSON, with relation fields included per the include clause.'
    ))
    story.append(p(
        'The same pattern is replicated by every resource endpoint: /api/revenue, /api/employees, '
        '/api/employee-costs, /api/allocations, /api/expenses, /api/expense-categories, '
        '/api/client-types, /api/locations, /api/departments, /api/employee-types. The '
        '<font name="DejaVuSans">/api/companies</font> route is slightly different because it '
        'returns the hierarchy tree rather than a flat list, but it still filters by accessible '
        'IDs (a Group Admin sees the full tree; a tenant user sees only their own tenant as a '
        'single-element list).'
    ))

    story.extend(h2('4.4 Profitability Calculation Logic'))
    story.append(p(
        'The <font name="DejaVuSans">GET /api/dashboard</font> endpoint is the most important '
        'aggregation in the suite. It produces the four KPIs, the four chart datasets, and the '
        'per-client profitability table that the dashboard renders. The pipeline below describes '
        'exactly what it does; the flow diagram visualises the high-level formula.'
    ))

    story.append(Spacer(1, 6))
    story.append(fit_image(os.path.join(BASE_DIR, 'diagram_flow.png'),
                            max_w=AVAIL_W, max_h=AVAIL_H * 0.45))
    story.append(caption(
        'Figure 2. Profitability calculation flow implemented by GET /api/dashboard. Revenue rows, '
        'employee-cost rows (allocated to clients via EmployeeClientAllocation), and other-expense '
        'rows feed the four KPIs and four chart datasets.'
    ))

    story.append(p(
        'The handler executes the following steps in order. <b>Step 1: gather revenue rows.</b> '
        'It calls <font name="DejaVuSans">db.revenue.findMany</font> with a where clause that '
        'filters on date range and on the client\'s companyId being in the target set (with optional '
        'locationId / clientTypeId filters applied on the client relation). It selects amount, '
        'date, clientId and the client\'s name. <b>Step 2: gather employee costs.</b> It calls '
        '<font name="DejaVuSans">db.employeeCost.findMany</font> with date range and on '
        '<font name="DejaVuSans">employee.companyId IN targetIds</font>. <b>Step 3: gather '
        'allocations.</b> It calls <font name="DejaVuSans">db.employeeClientAllocation.findMany</font> '
        'filtered by <font name="DejaVuSans">employee.companyId IN targetIds</font>, selecting '
        'employeeId, clientId, allocationPercent.'
    ))

    story.append(p(
        '<b>Step 4: build the employee-to-clients allocation map.</b> A <font name="DejaVuSans">Map<employeeId, '
        'Array<{clientId, pct}>></font> is built from the allocation rows. '
        '<b>Step 5: allocate employee cost to clients.</b> For each employee cost row, the cost '
        'amount is distributed across the employee\'s allocated clients proportionally: '
        '<font name="DejaVuSans">costByClient[clientId] += empCost.amount * pct / 100</font>. '
        'If the employee has no allocations, the cost is bucketed into '
        '<font name="DejaVuSans">__UNALLOCATED__</font> (and excluded from the per-client profit '
        'table). The same loop accumulates <font name="DejaVuSans">totalEmpCost</font>, '
        '<font name="DejaVuSans">empCostByType</font> (a map keyed by SALARY / ALLOWANCE / '
        'OVERTIME / BENEFIT / OTHER), and the monthly cost series.'
    ))

    story.append(p(
        '<b>Step 6: gather expenses.</b> <font name="DejaVuSans">db.expense.findMany</font> is '
        'called with date range and companyId filter; the resulting rows are aggregated by '
        'category name into <font name="DejaVuSans">expenseByCategory</font> and added to the '
        'monthly cost series. <b>Step 7: compute KPIs.</b> '
        '<font name="DejaVuSans">totalRevenue = sum(revenue.amount)</font>; '
        '<font name="DejaVuSans">totalCost = totalEmpCost + totalExpenses</font>; '
        '<font name="DejaVuSans">totalProfit = totalRevenue - totalCost</font>; '
        '<font name="DejaVuSans">profitMargin = (totalProfit / totalRevenue) * 100</font> '
        '(guarded against divide-by-zero).'
    ))

    story.append(p(
        '<b>Step 8: build chart datasets.</b> '
        '<i>revenueByClient</i>: the per-client revenue map is sorted descending, the top 6 are '
        'taken, and the remainder is summed into an "Others" bucket; the chart palette assigns '
        'one colour per slice. <i>costByCategory</i>: the employee-cost-type map is converted to '
        '"Emp · Salary", "Emp · Allowance", etc. entries, concatenated with the expense-by-category '
        'entries, sorted descending, and coloured. <i>profitByClient</i>: for every client ID '
        'appearing in either the revenue map or the cost map (excluding __UNALLOCATED__), '
        'profit = revenue − cost is computed, and the array is sorted by profit descending. '
        '<i>profitTrend</i>: the months in the requested date range are enumerated, and for each '
        'month the revenue, cost and profit are emitted as a triple.'
    ))

    story.append(p(
        'The handler returns a single JSON object: <font name="DejaVuSans">{ range, kpis, '
        'revenueByClient, costByCategory, profitByClient, profitTrend, companies }</font>. The '
        'frontend DashboardModule maps these directly into the KPI cards, charts and table. The '
        'formula can be summarised as: <b>TOTAL REVENUE − TOTAL COST = PROFIT → PROFIT MARGIN</b>.'
    ))

    story.extend(h2('4.5 Employee – Client Allocation'))
    story.append(p(
        'The <font name="DejaVuSans">EmployeeClientAllocation</font> junction table is the bridge '
        'that makes per-client profitability possible. Each row carries an employeeId, a clientId, '
        'an allocationPercent (Float, 0–100), and optional startDate / endDate fields. An '
        'employee can have multiple allocations — for example, an engineer could be 60% allocated '
        'to Client A and 40% to Client B, summing to 100%. The Allocations module UI groups '
        'allocations by employee, shows a horizontal stacked-bar visualisation with one segment '
        'per allocation (width proportional to allocationPercent), and a Total Allocation % '
        'badge: green when 100%, amber when incomplete (under 100%), rose when over-allocated '
        '(over 100%). The Add Allocation dialog restricts the Client dropdown to clients in the '
        'selected employee\'s company and shows a live "Current → Projected" projection that turns '
        'rose when the projected total exceeds 100%.'
    ))

    story.extend(h2('4.6 Custom Columns Feature (Companies Module)'))
    story.append(p(
        'The Companies module includes a Custom Columns feature that lets the Group Admin '
        'toggle the visibility of eight columns in the companies table (Code, Type, Status, '
        'Parent, Clients, Employees, Users, Created). The Company Name column is always visible '
        'and sticky. The feature is implemented with the modern React 18 '
        '<font name="DejaVuSans">useSyncExternalStore</font> hook, backed by a '
        '<font name="DejaVuSans">localStorage</font> entry at key '
        '<font name="DejaVuSans">drona.companies.columns</font>.'
    ))

    story.append(p(
        'The external store has three parts. <b>(a) subscribe(callback)</b> registers listeners '
        'for the browser\'s <font name="DejaVuSans">storage</font> event (which fires on '
        'cross-tab changes) and a custom <font name="DejaVuSans">drona:companies-cols-change</font> '
        'event (which fires on same-tab changes via <font name="DejaVuSans">window.dispatchEvent</font>). '
        '<b>(b) getSnapshot()</b> reads the JSON string from localStorage (returning the default '
        'set if the item is missing or unparseable). <b>(c) getServerSnapshot()</b> returns the '
        'default set so the server-rendered HTML matches the first client render — this prevents '
        'hydration mismatches. The visible set defaults to 6 of the 8 columns (Code, Type, Status, '
        'Clients, Employees, Users); "Show all" adds all 8; "Reset" restores the defaults. '
        'Preferences persist across page reloads and across browser tabs.'
    ))

    story.append(PageBreak())

    # ============================================================
    # CHAPTER 5 — Technology Stack
    # ============================================================
    story.extend(h1('Chapter 5 — Technology Stack'))

    story.append(p(
        'The Drona Profitability Suite is built on a modern, fully-typed JavaScript stack. '
        'The table below enumerates every significant dependency, its version, and the architectural '
        'role it plays. The non-negotiable core is Next.js 16.1.3 with the App Router; everything '
        'else is selected to either maximise type safety (TypeScript, Prisma, Zod), maximise '
        'developer velocity (shadcn/ui, Tailwind CSS 4), or provide best-of-breed UX primitives '
        '(Recharts, Framer Motion, Sonner).'
    ))

    tech_rows = [
        [Paragraph('<b>Layer</b>', TBL_HEADER),
         Paragraph('<b>Technology</b>', TBL_HEADER),
         Paragraph('<b>Version</b>', TBL_HEADER_C)],
        [Paragraph('Core Framework', TBL_CELL),
         Paragraph('Next.js (App Router, Turbopack)', TBL_CELL),
         Paragraph('16.1.3', TBL_CELL_C)],
        [Paragraph('Language', TBL_CELL),
         Paragraph('TypeScript', TBL_CELL),
         Paragraph('5', TBL_CELL_C)],
        [Paragraph('Styling', TBL_CELL),
         Paragraph('Tailwind CSS', TBL_CELL),
         Paragraph('4', TBL_CELL_C)],
        [Paragraph('UI Components', TBL_CELL),
         Paragraph('shadcn/ui (New York) + Radix UI primitives + lucide-react icons', TBL_CELL),
         Paragraph('0.525.0 (lucide)', TBL_CELL_C)],
        [Paragraph('Database ORM', TBL_CELL),
         Paragraph('Prisma (SQLite provider)', TBL_CELL),
         Paragraph('6.19.2', TBL_CELL_C)],
        [Paragraph('Database', TBL_CELL),
         Paragraph('SQLite (file at db/custom.db)', TBL_CELL),
         Paragraph('n/a', TBL_CELL_C)],
        [Paragraph('Charts', TBL_CELL),
         Paragraph('Recharts', TBL_CELL),
         Paragraph('2.15.4', TBL_CELL_C)],
        [Paragraph('Client State', TBL_CELL),
         Paragraph('Zustand', TBL_CELL),
         Paragraph('5.0.6', TBL_CELL_C)],
        [Paragraph('Server State', TBL_CELL),
         Paragraph('TanStack Query (available, used for caching)', TBL_CELL),
         Paragraph('5.82.0', TBL_CELL_C)],
        [Paragraph('Forms', TBL_CELL),
         Paragraph('React Hook Form + Zod', TBL_CELL),
         Paragraph('7.60.0 / 4.0.2', TBL_CELL_C)],
        [Paragraph('Animations', TBL_CELL),
         Paragraph('Framer Motion', TBL_CELL),
         Paragraph('12.23.2', TBL_CELL_C)],
        [Paragraph('Date utilities', TBL_CELL),
         Paragraph('date-fns', TBL_CELL),
         Paragraph('4.1.0', TBL_CELL_C)],
        [Paragraph('Notifications', TBL_CELL),
         Paragraph('Sonner', TBL_CELL),
         Paragraph('2.0.6', TBL_CELL_C)],
        [Paragraph('Authentication', TBL_CELL),
         Paragraph('Custom cookie-session (NextAuth.js v4 available, not used)', TBL_CELL),
         Paragraph('n/a', TBL_CELL_C)],
        [Paragraph('Theming', TBL_CELL),
         Paragraph('next-themes', TBL_CELL),
         Paragraph('0.4.6', TBL_CELL_C)],
        [Paragraph('AI SDK (future)', TBL_CELL),
         Paragraph('z-ai-web-dev-sdk (LLM, VLM, TTS, ASR, image generation)', TBL_CELL),
         Paragraph('0.0.18', TBL_CELL_C)],
        [Paragraph('Package Manager', TBL_CELL),
         Paragraph('Bun', TBL_CELL),
         Paragraph('n/a', TBL_CELL_C)],
        [Paragraph('Linting', TBL_CELL),
         Paragraph('ESLint + eslint-config-next', TBL_CELL),
         Paragraph('9', TBL_CELL_C)],
    ]
    story.append(Spacer(1, 6))
    story.append(make_table(tech_rows, [0.27, 0.55, 0.18]))
    story.append(caption('Table 3. Technology stack with exact versions (from package.json).'))

    story.extend(h2('5.1 Architectural Rationale'))
    story.append(p(
        '<b>Why Next.js App Router?</b> The App Router gives us server components and API routes '
        'in the same codebase, the same TypeScript types, and the same deployment artifact. '
        'Server components let us keep Prisma queries off the client bundle entirely — the '
        '<font name="DejaVuSans">/api/*</font> routes run server-side, use the Prisma client '
        'directly, and never leak database internals to the browser. Turbopack delivers '
        'sub-second hot reload during development, which materially improves iteration speed.'
    ))

    story.append(p(
        '<b>Why Prisma?</b> Prisma generates a fully-typed client from the schema, which means '
        'every <font name="DejaVuSans">findMany</font> call has autocomplete on its '
        '<font name="DejaVuSans">where</font> clause and on its <font name="DejaVuSans">include</font> '
        'clause. Schema migrations are declarative; <font name="DejaVuSans">bun run db:push</font> '
        'applies the schema to SQLite in one step. The SQLite provider is appropriate for the demo '
        'because it requires zero infrastructure — the database is a single file — and Prisma can '
        'be re-pointed at PostgreSQL or MySQL in production by changing the datasource provider '
        'and the connection URL.'
    ))

    story.append(p(
        '<b>Why Zustand over Redux?</b> Zustand delivers 90% of Redux\'s capability with ~5% of '
        'the boilerplate. The entire app store is 58 lines of code, including type definitions, '
        'and there is no ceremony around actions, reducers, or middleware. The store holds the '
        'current user, the loading flag, the active module, and the filter context (companyId, '
        'locationId, clientTypeId, from, to). For server state, TanStack Query is available and '
        'used for caching where beneficial.'
    ))

    story.append(p(
        '<b>Why shadcn/ui?</b> shadcn/ui gives us composable, accessible, themeable components '
        'built on top of Radix UI primitives, with full keyboard navigation and ARIA semantics. '
        'The components are copied into the project (not installed as a dependency), so they can '
        'be customised freely. The New York variant provides a tighter visual density than the '
        'default variant, which suits a data-heavy ERP interface.'
    ))

    story.append(PageBreak())

    # ============================================================
    # CHAPTER 6 — API Reference
    # ============================================================
    story.extend(h1('Chapter 6 — API Reference'))

    story.append(p(
        'All API endpoints live under <font name="DejaVuSans">/src/app/api/</font> and follow '
        'Next.js App Router conventions: a <font name="DejaVuSans">route.ts</font> file exports '
        'named <font name="DejaVuSans">GET</font> / <font name="DejaVuSans">POST</font> / '
        '<font name="DejaVuSans">DELETE</font> functions. Every authenticated route calls '
        '<font name="DejaVuSans">getCurrentUser()</font> first and returns HTTP 401 if no session '
        'is present. Every list endpoint is tenant-isolated via '
        '<font name="DejaVuSans">getAccessibleCompanyIds(user)</font>. The table below lists '
        'every endpoint with its method, purpose, tenant-isolation status, and role gate.'
    ))

    api_rows = [
        [Paragraph('<b>Method</b>', TBL_HEADER_C),
         Paragraph('<b>Path</b>', TBL_HEADER),
         Paragraph('<b>Purpose</b>', TBL_HEADER),
         Paragraph('<b>Tenant-isolated?</b>', TBL_HEADER_C),
         Paragraph('<b>Role gate</b>', TBL_HEADER_C)],
        [Paragraph('POST', TBL_CELL_C),
         Paragraph('/api/auth/login', TBL_CELL_MONO),
         Paragraph('Authenticate, returns user + sets drona_session cookie', TBL_CELL),
         Paragraph('N/A (auth)', TBL_CELL_C),
         Paragraph('Public', TBL_CELL_C)],
        [Paragraph('POST', TBL_CELL_C),
         Paragraph('/api/auth/logout', TBL_CELL_MONO),
         Paragraph('Destroy the session row + clear the cookie', TBL_CELL),
         Paragraph('N/A (auth)', TBL_CELL_C),
         Paragraph('Authenticated', TBL_CELL_C)],
        [Paragraph('GET', TBL_CELL_C),
         Paragraph('/api/auth/me', TBL_CELL_MONO),
         Paragraph('Return the current user from the session cookie', TBL_CELL),
         Paragraph('N/A (auth)', TBL_CELL_C),
         Paragraph('Authenticated', TBL_CELL_C)],
        [Paragraph('GET / POST', TBL_CELL_C),
         Paragraph('/api/companies', TBL_CELL_MONO),
         Paragraph('List the company hierarchy / create a new tenant', TBL_CELL),
         Paragraph('Yes', TBL_CELL_C),
         Paragraph('GET: all; POST: GROUP_ADMIN', TBL_CELL_C)],
        [Paragraph('GET / POST', TBL_CELL_C),
         Paragraph('/api/clients', TBL_CELL_MONO),
         Paragraph('List / create clients (filtered by accessible companies)', TBL_CELL),
         Paragraph('Yes', TBL_CELL_C),
         Paragraph('All (POST: not STANDARD_USER)', TBL_CELL_C)],
        [Paragraph('GET / POST', TBL_CELL_C),
         Paragraph('/api/revenue', TBL_CELL_MONO),
         Paragraph('List / create revenue entries', TBL_CELL),
         Paragraph('Yes', TBL_CELL_C),
         Paragraph('All (POST: not STANDARD_USER)', TBL_CELL_C)],
        [Paragraph('GET / POST', TBL_CELL_C),
         Paragraph('/api/employees', TBL_CELL_MONO),
         Paragraph('List / create employees', TBL_CELL),
         Paragraph('Yes', TBL_CELL_C),
         Paragraph('All (POST: not STANDARD_USER)', TBL_CELL_C)],
        [Paragraph('GET / POST', TBL_CELL_C),
         Paragraph('/api/employee-costs', TBL_CELL_MONO),
         Paragraph('List / create employee cost entries (UI module removed; API retained for dashboard)', TBL_CELL),
         Paragraph('Yes', TBL_CELL_C),
         Paragraph('All (POST: not STANDARD_USER)', TBL_CELL_C)],
        [Paragraph('GET / POST', TBL_CELL_C),
         Paragraph('/api/allocations', TBL_CELL_MONO),
         Paragraph('List / create employee-client allocations', TBL_CELL),
         Paragraph('Yes', TBL_CELL_C),
         Paragraph('All (POST: not STANDARD_USER)', TBL_CELL_C)],
        [Paragraph('DELETE', TBL_CELL_C),
         Paragraph('/api/allocations?id=', TBL_CELL_MONO),
         Paragraph('Delete a single allocation row by ID', TBL_CELL),
         Paragraph('Yes', TBL_CELL_C),
         Paragraph('All (not STANDARD_USER)', TBL_CELL_C)],
        [Paragraph('GET / POST', TBL_CELL_C),
         Paragraph('/api/expenses', TBL_CELL_MONO),
         Paragraph('List / create expenses (categorised)', TBL_CELL),
         Paragraph('Yes', TBL_CELL_C),
         Paragraph('All (POST: not STANDARD_USER)', TBL_CELL_C)],
        [Paragraph('GET', TBL_CELL_C),
         Paragraph('/api/expense-categories', TBL_CELL_MONO),
         Paragraph('List expense categories (per tenant)', TBL_CELL),
         Paragraph('Yes', TBL_CELL_C),
         Paragraph('All', TBL_CELL_C)],
        [Paragraph('GET', TBL_CELL_C),
         Paragraph('/api/client-types', TBL_CELL_MONO),
         Paragraph('List reference client types (Enterprise, SMB, Strategic, Retail)', TBL_CELL),
         Paragraph('Global', TBL_CELL_C),
         Paragraph('All', TBL_CELL_C)],
        [Paragraph('GET', TBL_CELL_C),
         Paragraph('/api/locations', TBL_CELL_MONO),
         Paragraph('List reference locations (Mumbai, Bengaluru, Delhi, Hyderabad, Pune)', TBL_CELL),
         Paragraph('Global', TBL_CELL_C),
         Paragraph('All', TBL_CELL_C)],
        [Paragraph('GET', TBL_CELL_C),
         Paragraph('/api/departments', TBL_CELL_MONO),
         Paragraph('List reference departments (Engineering, Sales, Delivery, Operations, HR, Finance)', TBL_CELL),
         Paragraph('Global', TBL_CELL_C),
         Paragraph('All', TBL_CELL_C)],
        [Paragraph('GET', TBL_CELL_C),
         Paragraph('/api/employee-types', TBL_CELL_MONO),
         Paragraph('List reference employee types (Full-time, Part-time, Contractor)', TBL_CELL),
         Paragraph('Global', TBL_CELL_C),
         Paragraph('All', TBL_CELL_C)],
        [Paragraph('GET', TBL_CELL_C),
         Paragraph('/api/dashboard', TBL_CELL_MONO),
         Paragraph('KPIs + chart data; accepts companyId, locationId, clientTypeId, from, to filters', TBL_CELL),
         Paragraph('Yes', TBL_CELL_C),
         Paragraph('All', TBL_CELL_C)],
        [Paragraph('GET', TBL_CELL_C),
         Paragraph('/api/reports/profitability', TBL_CELL_MONO),
         Paragraph('Per-company profitability report (parent row + tenant rows)', TBL_CELL),
         Paragraph('Yes', TBL_CELL_C),
         Paragraph('GROUP_ADMIN, COMPANY_ADMIN', TBL_CELL_C)],
    ]
    story.append(Spacer(1, 6))
    story.append(make_table(api_rows, [0.08, 0.22, 0.40, 0.13, 0.17]))
    story.append(caption('Table 4. Complete API reference. Every list endpoint is tenant-isolated via getAccessibleCompanyIds(user).'))

    story.append(PageBreak())

    # ============================================================
    # CHAPTER 7 — Data Model
    # ============================================================
    story.extend(h1('Chapter 7 — Data Model'))

    story.append(p(
        'The Prisma schema defines 13 models. They fall into four logical groups: <b>Auth & Tenancy</b> '
        '(User, Session, Company), <b>Reference / Master Data</b> (ClientType, Location, '
        'EmployeeType, Department), <b>Business Modules</b> (Client, Revenue, Employee, '
        'EmployeeCost, EmployeeClientAllocation, ExpenseCategory, Expense). The table below '
        'enumerates every model with its purpose, its key fields and its relationships.'
    ))

    prisma_rows = [
        [Paragraph('<b>Model</b>', TBL_HEADER),
         Paragraph('<b>Purpose</b>', TBL_HEADER),
         Paragraph('<b>Key Fields</b>', TBL_HEADER),
         Paragraph('<b>Relationships</b>', TBL_HEADER)],
        [Paragraph('<b>User</b>', TBL_CELL),
         Paragraph('Application user with role + tenant attachment', TBL_CELL),
         Paragraph('id, email (unique), name, passwordHash, role, companyId?, active, timestamps', TBL_CELL),
         Paragraph('Belongs to Company (optional). Has many Sessions.', TBL_CELL)],
        [Paragraph('<b>Session</b>', TBL_CELL),
         Paragraph('Server-side session token with 12h expiry', TBL_CELL),
         Paragraph('id, userId, token (unique UUID), expiresAt, createdAt', TBL_CELL),
         Paragraph('Belongs to User (cascade delete).', TBL_CELL)],
        [Paragraph('<b>Company</b>', TBL_CELL),
         Paragraph('Parent or tenant company in the hierarchy', TBL_CELL),
         Paragraph('id, name, code (unique), type (PARENT|TENANT), parentId?, status, timestamps', TBL_CELL),
         Paragraph('Self-relation via "CompanyHierarchy" (parentId). Has many Users, Clients, Employees, Expenses, Categories.', TBL_CELL)],
        [Paragraph('<b>ClientType</b>', TBL_CELL),
         Paragraph('Reference type for a client', TBL_CELL),
         Paragraph('id, name (unique), createdAt', TBL_CELL),
         Paragraph('Has many Clients.', TBL_CELL)],
        [Paragraph('<b>Location</b>', TBL_CELL),
         Paragraph('Reference geographic location', TBL_CELL),
         Paragraph('id, name (unique), country?, createdAt', TBL_CELL),
         Paragraph('Has many Clients, Employees.', TBL_CELL)],
        [Paragraph('<b>EmployeeType</b>', TBL_CELL),
         Paragraph('Reference type for an employee', TBL_CELL),
         Paragraph('id, name (unique), createdAt', TBL_CELL),
         Paragraph('Has many Employees.', TBL_CELL)],
        [Paragraph('<b>Department</b>', TBL_CELL),
         Paragraph('Reference department', TBL_CELL),
         Paragraph('id, name (unique), createdAt', TBL_CELL),
         Paragraph('Has many Employees.', TBL_CELL)],
        [Paragraph('<b>Client</b>', TBL_CELL),
         Paragraph('A client billed by a tenant', TBL_CELL),
         Paragraph('id, companyId, name, code, clientTypeId, locationId, status, contractValue?, contactName?, contactEmail?', TBL_CELL),
         Paragraph('Belongs to Company, ClientType, Location. Has many Revenue, EmployeeClientAllocation. Unique [companyId, code].', TBL_CELL)],
        [Paragraph('<b>Revenue</b>', TBL_CELL),
         Paragraph('Invoice entry billed to a client', TBL_CELL),
         Paragraph('id, clientId, date, invoiceNo, description?, quantity, rate, amount, timestamps', TBL_CELL),
         Paragraph('Belongs to Client (cascade delete).', TBL_CELL)],
        [Paragraph('<b>Employee</b>', TBL_CELL),
         Paragraph('A worker employed by a tenant', TBL_CELL),
         Paragraph('id, companyId, name, code, employeeTypeId, departmentId, locationId, designation?, salary, status, joiningDate?', TBL_CELL),
         Paragraph('Belongs to Company, EmployeeType, Department, Location. Has many EmployeeCost, EmployeeClientAllocation. Unique [companyId, code].', TBL_CELL)],
        [Paragraph('<b>EmployeeCost</b>', TBL_CELL),
         Paragraph('A salary/allowance/benefit cost row for an employee', TBL_CELL),
         Paragraph('id, employeeId, date, costType (SALARY|ALLOWANCE|OVERTIME|BENEFIT|OTHER), amount, description?', TBL_CELL),
         Paragraph('Belongs to Employee (cascade delete).', TBL_CELL)],
        [Paragraph('<b>EmployeeClientAllocation</b>', TBL_CELL),
         Paragraph('Junction: how an employee\'s time is split across clients (%)', TBL_CELL),
         Paragraph('id, employeeId, clientId, allocationPercent, startDate?, endDate?', TBL_CELL),
         Paragraph('Belongs to Employee + Client (both cascade delete). This is the M:N bridge.', TBL_CELL)],
        [Paragraph('<b>ExpenseCategory</b>', TBL_CELL),
         Paragraph('Tenant-owned expense category (e.g. Rent, Travel)', TBL_CELL),
         Paragraph('id, companyId, name, type (OPERATIONAL|ADMINISTRATIVE|CAPITAL), timestamps', TBL_CELL),
         Paragraph('Belongs to Company. Has many Expenses. Unique [companyId, name].', TBL_CELL)],
        [Paragraph('<b>Expense</b>', TBL_CELL),
         Paragraph('A categorised expense row booked by a tenant', TBL_CELL),
         Paragraph('id, companyId, categoryId, date, amount, description?, timestamps', TBL_CELL),
         Paragraph('Belongs to Company + ExpenseCategory (cascade delete).', TBL_CELL)],
    ]
    story.append(Spacer(1, 6))
    story.append(make_table(prisma_rows, [0.18, 0.22, 0.32, 0.28]))
    story.append(caption('Table 5. The 13 Prisma models with their purposes, key fields and relationships.'))

    story.extend(h2('7.1 Seeded Sample Dataset'))
    story.append(p(
        'The seed script (<font name="DejaVuSans">prisma/seed.ts</font>) is idempotent and '
        'produces a realistic dataset that exercises every model and every API route. It creates '
        'one parent company (Drona Enterprises), two tenant companies (Drona Logitech, Drona '
        'Valuechain), five demo users (one Group Admin, two Company Admins, two Standard Users), '
        'four client types, five locations, three employee types, six departments, seven clients '
        '(four under Logitech, three under Valuechain), nine employees (five under Logitech, four '
        'under Valuechain), approximately 42 revenue records dated April – September 2024, 162 '
        'employee cost records, 19 employee-client allocations, 10 expense categories, and 60 '
        'expense records. The aggregate KPIs the dashboard produces against this dataset are '
        'Rs. 21.12 Cr total revenue, Rs. 5.53 Cr total cost (Rs. 4.13 Cr employee cost + Rs. 1.40 Cr '
        'other expenses), Rs. 15.59 Cr total profit, and 73.8% profit margin.'
    ))

    story.append(PageBreak())

    # ============================================================
    # CHAPTER 8 — Security & Isolation
    # ============================================================
    story.extend(h1('Chapter 8 — Security & Isolation'))

    story.append(p(
        'Security in the Drona Profitability Suite rests on five pillars: cookie-session '
        'authentication, server-side tenant access control, role-based UI gating, parameterised '
        'queries (via Prisma), and React\'s default XSS escaping. The sections below discuss each '
        'in turn, including the explicit demo-grade shortcuts that are not acceptable for '
        'production deployment.'
    ))

    story.extend(h2('8.1 Cookie-Session Authentication'))
    story.append(p(
        'Authentication uses an httpOnly cookie named <font name="DejaVuSans">drona_session</font> '
        'with <font name="DejaVuSans">sameSite=lax</font> and <font name="DejaVuSans">path=/</font>. '
        'The cookie value is a random UUID token (generated via <font name="DejaVuSans">crypto.randomUUID()</font>) '
        'that is also stored in the Session table alongside the userId and an '
        '<font name="DejaVuSans">expiresAt</font> timestamp. The session TTL is hard-coded at '
        '12 hours. On every authenticated request, <font name="DejaVuSans">getCurrentUser()</font> '
        'looks up the session, checks the expiry (deleting the row if expired), and verifies the '
        'user is still <font name="DejaVuSans">active</font>. The httpOnly flag prevents '
        'client-side JavaScript from reading the cookie; sameSite=lax prevents CSRF in the '
        'common case (the cookie is not sent on cross-site POST requests).'
    ))

    story.extend(h2('8.2 Tenant Access Control'))
    story.append(p(
        'The function <font name="DejaVuSans">getAccessibleCompanyIds(user)</font> is the single '
        'chokepoint for tenant isolation. As described in Chapter 4, it returns either every '
        'company ID (for a Group Admin) or a single-element array of the user\'s own companyId. '
        'Every list / create API route calls this function and filters its Prisma query on '
        '<font name="DejaVuSans">companyId IN accessibleIds</font>. Write operations verify the '
        'target company is in the accessible set before persisting. This means a tenant user '
        'cannot read or write another tenant\'s data even by crafting a custom request with '
        'a foreign companyId in the body.'
    ))

    story.extend(h2('8.3 Role-Based UI Gating'))
    story.append(p(
        'The AppShell filters the navigation array by role: Companies is restricted to '
        'GROUP_ADMIN; Reports is restricted to GROUP_ADMIN and COMPANY_ADMIN; the other six '
        'modules are visible to all roles. Add buttons in operational modules are disabled for '
        'STANDARD_USER (replaced by a "View-only access" badge). These UI restrictions are '
        'defence-in-depth — the backend re-checks authorisation on every request — but they '
        'reduce user confusion by hiding controls the user cannot use.'
    ))

    story.extend(h2('8.4 Demo-Grade Password Hashing (Explicit Caveat)'))
    story.append(p(
        'The current password hashing is the literal byte-reversal of the password prefixed with '
        'the marker <font name="DejaVuSans">demo$</font>. This is documented as <b>NOT suitable '
        'for production</b>; it exists only so the seed script can produce demo accounts without '
        'pulling in a bcrypt native dependency. A production deployment must replace '
        '<font name="DejaVuSans">verifyPassword</font> with bcrypt or argon2 and migrate the '
        'existing hashes on next user login. The auth.ts file structure (a single function to '
        'swap) makes this change a one-commit refactor.'
    ))

    story.extend(h2('8.5 SQL Injection & XSS'))
    story.append(p(
        'SQL injection is mitigated by Prisma\'s parameterised queries — every '
        '<font name="DejaVuSans">findMany</font> / <font name="DejaVuSans">create</font> / '
        '<font name="DejaVuSans">deleteMany</font> call compiles to a parameterised SQL statement '
        'with no string concatenation of user input. Cross-site scripting is mitigated by '
        'React\'s default escaping of all interpolated values; the codebase contains no '
        '<font name="DejaVuSans">dangerouslySetInnerHTML</font> usage. CSRF is mitigated by the '
        'sameSite=lax cookie attribute; no separate CSRF token is issued because the Same-Origin '
        'Policy and sameSite=lax together prevent the relevant attack vectors for an internal '
        'B2B ERP.'
    ))

    story.append(PageBreak())

    # ============================================================
    # CHAPTER 9 — Key Features & Innovations
    # ============================================================
    story.extend(h1('Chapter 9 — Key Features & Innovations'))

    story.append(p(
        'The Drona Profitability Suite ships with six features that, taken together, distinguish '
        'it from a generic CRUD scaffold. Each is described below with the implementation detail '
        'that makes it work.'
    ))

    story.extend(h3('9.1 Backend-Enforced Multi-Tenant Data Isolation'))
    story.append(p(
        'Tenant isolation is enforced at the API layer via <font name="DejaVuSans">getAccessibleCompanyIds(user)</font>, '
        'not by hiding UI controls. A tenant user cannot read or write another tenant\'s data even '
        'by direct API call. This is the single most important security guarantee in the suite, '
        'and it is implemented as a 6-line function called by every authenticated route.'
    ))

    story.extend(h3('9.2 Profitability Calculation with Employee-Cost Allocation'))
    story.append(p(
        'The dashboard\'s cost engine distributes each employee\'s monthly cost across the clients '
        'they are allocated to, proportional to the allocation percentage. An employee 60% on '
        'Client A and 40% on Client B will see their Rs. 1,00,000 salary split as Rs. 60,000 to '
        'Client A and Rs. 40,000 to Client B. This is the calculation that turns raw cost rows '
        'into per-client profitability, and it is implemented in the '
        '<font name="DejaVuSans">/api/dashboard</font> endpoint in roughly 30 lines of TypeScript '
        'using a Map-based accumulator.'
    ))

    story.extend(h3('9.3 Custom Columns with useSyncExternalStore + localStorage'))
    story.append(p(
        'The Companies module\'s Custom Columns feature uses the modern React 18 '
        '<font name="DejaVuSans">useSyncExternalStore</font> hook to back column visibility by '
        '<font name="DejaVuSans">localStorage</font>. The store is subscribed via both the '
        'browser\'s <font name="DejaVuSans">storage</font> event (cross-tab) and a custom '
        '<font name="DejaVuSans">drona:companies-cols-change</font> event (same-tab), so column '
        'toggles in one tab propagate to all open tabs in real time. The server snapshot returns '
        'the default set, preventing hydration mismatches.'
    ))

    story.extend(h3('9.4 Mobile-Responsive Sidebar'))
    story.append(p(
        'On screens narrower than the <font name="DejaVuSans">lg</font> breakpoint (1024px), '
        'the vertical sidebar disappears and is replaced by a horizontal scroller of module pills '
        'in the header. The scroller uses a thin custom scrollbar style '
        '(<font name="DejaVuSans">scroll-thin</font> class) and shows the module icon plus label. '
        'On desktop, the sidebar reverts to a 256px-wide vertical column with role-filtered '
        'navigation, accent-coloured icon tiles per module, and a tenant-context panel at the '
        'bottom.'
    ))

    story.extend(h3('9.5 Quick-Login Shortcuts'))
    story.append(p(
        'The login screen ships with four quick-login shortcut buttons (Group Admin, Logitech '
        'Admin, Valuechain Admin, Logitech Standard User) that pre-fill the email and password '
        'fields. This makes demo and review cycles faster — a reviewer can click one button, hit '
        'submit, and be in the app as a specific role. The shortcuts are visible only on the '
        'login page and are removed once a session is established.'
    ))

    story.extend(h3('9.6 Comprehensive Seed Data'))
    story.append(p(
        'The seed script produces a dataset rich enough to make every KPI and every chart '
        'visually meaningful out of the box: 7 clients, 9 employees, ~42 revenue entries dated '
        'April – September 2024, 162 employee cost rows, 19 allocations, 60 expenses across 10 '
        'categories. The dashboard renders with four populated KPI cards, four populated charts '
        'and a populated per-client profitability table without any further data entry. This '
        'lets reviewers verify the application\'s behaviour immediately after '
        '<font name="DejaVuSans">bun run db:seed</font>.'
    ))

    story.append(PageBreak())

    # ============================================================
    # CHAPTER 10 — Conclusion & Future Enhancements
    # ============================================================
    story.extend(h1('Chapter 10 — Conclusion & Future Enhancements'))

    story.append(p(
        'The Drona Profitability Suite delivers a complete, browser-verified, multi-tenant ERP '
        'for staffing/consulting-style organisations that need per-client profitability '
        'tracking. It comprises 13 Prisma models, 8 user-facing modules, 17 API endpoints, 3 '
        'roles, and a comprehensive seed dataset that produces realistic KPIs (Rs. 21.12 Cr '
        'revenue, 73.8% margin) out of the box. The application passes <font name="DejaVuSans">bun run lint</font> '
        'with zero errors, every API route returns HTTP 200 in the smoke test, and multi-tenant '
        'data isolation is enforced at the backend via '
        '<font name="DejaVuSans">getAccessibleCompanyIds(user)</font>.'
    ))

    story.append(p(
        'The deliverable was scoped as a demo-grade artefact: it demonstrates the architecture '
        'and the user experience without claiming production readiness. The most important '
        'shortcut — the demo-grade password hashing — is documented in Chapter 8 and is a '
        'one-commit refactor away from production-safe. The other production gaps are smaller: '
        'no audit log, no CSV/PDF export, no fiscal-year configuration, no real-time '
        'notifications. These are addressed in the future-enhancements list below.'
    ))

    story.extend(h2('10.1 Suggested Future Work'))
    story.append(p(
        '<b>Production-grade password hashing.</b> Replace '
        '<font name="DejaVuSans">verifyPassword</font> with argon2 (preferred) or bcrypt. Migrate '
        'existing hashes on next login. Estimated effort: 1 commit + a migration script.'
    ))
    story.append(p(
        '<b>JWT-based sessions for horizontal scaling.</b> The current server-side Session table '
        'requires session affinity (sticky sessions) at the load balancer. Moving to signed JWTs '
        'with short expiry and a refresh-token rotation would let the app scale horizontally '
        'without sticky sessions, at the cost of more complex revocation.'
    ))
    story.append(p(
        '<b>Audit logging.</b> Persist every write operation (POST / DELETE) with userId, '
        'timestamp, target entity ID, and the diff. Useful for compliance and for debugging '
        '"who changed this number?" queries.'
    ))
    story.append(p(
        '<b>CSV / PDF export.</b> Add an "Export" button to the Revenue, Expenses and Reports '
        'modules that produces a CSV or PDF of the current filter scope. The Reports module is '
        'the highest-value target.'
    ))
    story.append(p(
        '<b>Role-based field-level permissions.</b> Today the role gate is binary (STANDARD_USER '
        'cannot add). A finer-grained system would let STANDARD_USER edit certain fields '
        '(description, contact email) but not others (contract value).'
    ))
    story.append(p(
        '<b>Real-time notifications via WebSocket.</b> Push updates to the dashboard when new '
        'revenue or expense rows are added by another user. Useful when multiple admins are '
        'working simultaneously.'
    ))
    story.append(p(
        '<b>Currency multi-support.</b> Today every amount is implicitly INR. Adding a currency '
        'column on Company and a conversion layer would let the suite serve multi-currency '
        'organisations.'
    ))
    story.append(p(
        '<b>Fiscal year configuration.</b> Today the date range defaults to April – September '
        '2024 (hard-coded in the Zustand store). A fiscal-year setting on Company would let each '
        'tenant configure their own default range.'
    ))

    story.append(Spacer(1, 12))
    story.append(p(
        '<b>Final note.</b> The application is browser-verified interactive: login works, all '
        'eight modules render with real data, every API route returns 200, role gating and tenant '
        'isolation are enforced end-to-end, the dashboard renders the seeded KPIs '
        '(Rs. 21.12 Cr / Rs. 5.53 Cr / Rs. 15.59 Cr / 73.8%) and all four charts populate '
        'correctly. The codebase is ready for a production-hardening pass.'
    ))

    return story


# ─────────────────────────────────────────────────────────────────────
# Build
# ─────────────────────────────────────────────────────────────────────
def build_body(output_path):
    doc = TocDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=LEFT_M, rightMargin=RIGHT_M,
        topMargin=TOP_M, bottomMargin=BOT_M,
        title='Drona Enterprises Profitability Suite — Technical Report',
        author='Z.ai Engineering',
        subject='Multi-Tenant Profitability SaaS Architecture',
        creator='Z.ai PDF Skill (ReportLab)',
    )
    story = build_story()
    doc.multiBuild(story, onFirstPage=header_footer, onLaterPages=header_footer)
    print(f'Body PDF built: {output_path}')


def merge_cover(cover_pdf, body_pdf, output_pdf):
    from pypdf import PdfReader, PdfWriter
    from pypdf.generic import RectangleObject
    A4_W, A4_H = 595.28, 841.89

    def normalize(page):
        # Always re-scale the page box to exact A4 so the merged document has
        # uniform page sizes (pdf_qa.py rejects even sub-pt mismatches).
        box = page.mediabox
        w, h = float(box.width), float(box.height)
        if abs(w - A4_W) > 0.1 or abs(h - A4_H) > 0.1:
            page.scale_to(A4_W, A4_H)
        # Force the mediabox/cropbox to exact A4 (scale_to leaves a tiny drift)
        page.mediabox = RectangleObject([0, 0, A4_W, A4_H])
        page.cropbox = RectangleObject([0, 0, A4_W, A4_H])
        return page

    writer = PdfWriter()
    cover_page = PdfReader(cover_pdf).pages[0]
    writer.add_page(normalize(cover_page))
    for page in PdfReader(body_pdf).pages:
        writer.add_page(normalize(page))
    writer.add_metadata({
        '/Title': 'Drona Enterprises Profitability Suite — Technical Report',
        '/Author': 'Z.ai Engineering',
        '/Subject': 'Multi-Tenant Profitability SaaS Architecture',
        '/Creator': 'Z.ai PDF Skill (ReportLab)',
        '/Producer': 'ReportLab + pypdf',
    })
    with open(output_pdf, 'wb') as f:
        writer.write(f)
    print(f'Final PDF (cover + body merged): {output_pdf}')


if __name__ == '__main__':
    body_pdf = os.path.join(BASE_DIR, '_body.pdf')
    cover_pdf = os.path.join(BASE_DIR, 'cover.pdf')
    final_pdf = os.path.join(BASE_DIR, 'Drona_Profitability_Suite_Technical_Report.pdf')

    build_body(body_pdf)
    merge_cover(cover_pdf, body_pdf, final_pdf)

    # Clean up intermediate body file
    if os.path.exists(body_pdf):
        os.remove(body_pdf)
    print('Done.')
